# Generated by Django 3.0.2 on 2020-05-27 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='emp_id',
            field=models.UUIDField(null=True),
        ),
    ]
