# Generated by Django 3.0.2 on 2020-05-27 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_userinfo_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='emp_id',
            field=models.CharField(auto_created=True, blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
