# Generated by Django 3.0.2 on 2020-05-28 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_auto_20200527_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='designation',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
