# Generated by Django 3.0.2 on 2020-05-28 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0006_userinfo_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='invalid_login_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='last_invalid_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
